follow up fix for PXB-2274 xtrabackup restore failed when there are DML statements running during backup stage.
percona/percona-xtrabackup pull request #1036
Opened 2021-02-05 14:37 UTC by rahulmalik87

stopping the apply log at exact LSN. previously It was processing the last block.

2021-02-05 14:38 UTC, rahulmalik87 commented
https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/37/

2021-02-11 07:07 UTC, satya-bodapati requested changes
Add appropriate comments please in the source code.

Can we put debug assertion in debug builds that verifies the stopped LSN is < log_status.last_checkpoint_lsn? (after redo copy is over)

And print a warning message in case we couldn't.

2021-02-11 12:45 UTC, rahulmalik87 commented
> Add appropriate comments please in the source code.
> 
> Can we put debug assertion in debug builds that verifies the stopped LSN is < log_status.last_checkpoint_lsn? (after redo copy is over)
> 
> And print a warning message in case we couldn't.

We already error out in case stopped LSN is < last_checkpoint_lsn.  
https://github.com/percona/percona-xtrabackup/blob/61756584cf08136774aa3e4cae93dca0f54c2646/storage/innobase/xtrabackup/src/redo_log.cc#L1203

2021-02-12 12:54 UTC, satya-bodapati commented
> > Add appropriate comments please in the source code.
> > Can we put debug assertion in debug builds that verifies the stopped LSN is < log_status.last_checkpoint_lsn? (after redo copy is over)
> > And print a warning message in case we couldn't.
> 
> We already error out in case stopped LSN is < last_checkpoint_lsn.
> 
> https://github.com/percona/percona-xtrabackup/blob/61756584cf08136774aa3e4cae93dca0f54c2646/storage/innobase/xtrabackup/src/redo_log.cc#L1203

What if scanned_lsn is way more than checkpoint_lsn? then we don't assert right? My suggestion is that we assert that we stopped exactly the checkpiont_lsn

2021-02-15 05:52 UTC, satya-bodapati requested changes

2021-02-15 05:52 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/redo_log.cc
> +#ifndef DBUG_OFF
This warning makes sense independent of build type

2021-02-15 05:52 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/redo_log.cc
> +
ut_ad(scanned_lsn <= stop_lsn);

2021-02-15 05:52 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/redo_log.cc
> +
I want this assertion after the redo copy is over. Or after the redo thread/file is closed.

2021-02-15 05:52 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +
remove spurios new line

2021-02-16 06:43 UTC, satya-bodapati requested changes

2021-02-16 06:43 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/redo_log.cc
> +  ut_ad(scanned_lsn >= stop_lsn);
I think the assertion is wrong. Please check
May be use ut_ad(scanned_lsn == stop_lsn);

2021-02-16 06:43 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/redo_log.cc
> +        last_checkpoint_lsn, scanned_lsn);
last_checkpoint_lsn?  you should use scanned_lsn

2021-02-17 07:03 UTC, satya-bodapati approved these changes

2021-02-18 06:51 UTC, rahulmalik87 commented
latest test result with debug assert https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/lastCompletedBuild/testReport/

2021-02-18 22:01 UTC, rahulmalik87 commented
latest test result with debug assert. https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/45/

2021-02-19 06:32 UTC, satya-bodapati approved these changes

2021-02-19 08:13 UTC, merged