PXB-2444: SELinux module adjusted for xbcloud
percona/percona-xtrabackup pull request #1060
Opened 2021-03-23 12:12 UTC by kamil-holubicki

https://jira.percona.com/browse/PXB-2444

1. Added rules needed by xbcloud
2. Cleanup around tmp and backup target directory related rules

2021-03-23 12:12 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1060) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1060) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtrabackup?pullRequest=1060) it.</sub>

2021-03-24 11:09 UTC, altmannmarcelo requested changes
xbcloud issue is fixed. However, xtrabackup is creating the --target-dir directory using `user_home_dir_t` context and we are missing policies for those.

2021-03-24 12:12 UTC, kamil-holubicki commented
@altmannmarcelo Fixed by adding file transition rule for directories created by xtrabackup directly in user's home directory.

2021-03-31 18:49 UTC, altmannmarcelo commented
LGTM

2021-03-31 18:49 UTC, altmannmarcelo approved these changes

2021-04-02 08:47 UTC, merged