PXB-2442: Backup cannot be decompressed using the apparmor profile
percona/percona-xtrabackup pull request #1064
Opened 2021-03-24 14:28 UTC by kamil-holubicki

https://jira.percona.com/browse/PXB-2442

Allowed usage of qpress and lz4.

2021-04-01 11:48 UTC, altmannmarcelo requested changes
qpress still failing:

```
vagrant@ubuntu-focal:~$ xtrabackup --decompress --target_dir=$HOME/dbbackup_PS8/full 2>&1 | tee decompress_full_backup_$(date +"%d_%m_%Y")_log
xtrabackup: recognized server arguments: --datadir=/var/lib/mysql
xtrabackup: recognized client arguments: --decompress=1 --target-dir=/home/vagrant/dbbackup_PS8/full
xtrabackup version 8.0.23-16 based on MySQL server 8.0.23 Linux (x86_64) (revision id: 934bc8f)
210401 11:38:30 [01] decompressing ./ibdata1.qp
sh: 1: qpress: Permission denied
cat: write error: Broken pipe
Error: decrypt and decompress thread 0 failed.
vagrant@ubuntu-focal:~$
```

Backup now complains about awk:
```
vagrant@ubuntu-focal:~$ sudo xtrabackup --user=vagrant --password='Passw0rd!' --backup --target-dir=$HOME/dbbackup_PS8 --encrypt=AES256 --encrypt-key=mHU3Zs5sRcSB7zB/JP1BInPP5lgShKly --encrypt-threads=10 --encrypt-chunk-size=128K --compress --compress-threads=10 --stream=xbstream --parallel=10 > $HOME/dbbackup_PS8/fullbackup.xbstream
xtrabackup: recognized server arguments: --datadir=/var/lib/mysql
xtrabackup: recognized client arguments: --user=vagrant --password=* --backup=1 --target-dir=/home/vagrant/dbbackup_PS8 --encrypt=AES256 --encrypt-key=* --encrypt-threads=10 --encrypt-chunk-size=128K --compress --compress-threads=10 --stream=xbstream --parallel=10
xtrabackup version 8.0.23-16 based on MySQL server 8.0.23 Linux (x86_64) (revision id: 934bc8f)
210401 11:46:27  version_check Connecting to MySQL server with DSN 'dbi:mysql:;mysql_read_default_group=xtrabackup' as 'vagrant'  (using password: YES).
210401 11:46:27  version_check Connected to MySQL server
210401 11:46:27  version_check Executing a version check against the server...
sh: 1: awk: Permission denied
```

2021-04-01 11:55 UTC, mchawla16 requested changes
Hi Kamil,
I am getting the following errors in /var/log/syslog after running backup:
`Apr  1 11:48:57 focal64new kernel: [604839.364567] audit: type=1400 audit(1617277737.517:131): apparmor="DENIED" operation="exec" profile="/usr/bin/xtrabackup" name="/usr/bin/gawk" pid=558861 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Apr  1 11:48:57 focal64new kernel: [604839.364872] audit: type=1400 audit(1617277737.517:132): apparmor="DENIED" operation="exec" profile="/usr/bin/xtrabackup" name="/usr/bin/gawk" pid=558861 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Apr  1 11:48:57 focal64new kernel: [604839.366014] audit: type=1400 audit(1617277737.517:133): apparmor="DENIED" operation="exec" profile="/usr/bin/xtrabackup" name="/usr/bin/grep" pid=558862 comm="perl" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Apr  1 11:48:57 focal64new kernel: [604839.366018] audit: type=1400 audit(1617277737.517:134): apparmor="DENIED" operation="exec" profile="/usr/bin/xtrabackup" name="/usr/bin/grep" pid=558862 comm="perl" requested_mask="x" denied_mask="x" fsuid=0 ouid=0`
Please check. Thanks.

2021-04-02 08:46 UTC, kamil-holubicki commented
Both issues fixed.

2021-04-02 11:17 UTC, altmannmarcelo approved these changes
LGTM

2021-04-06 10:06 UTC, merged