Fixed PXB-2500 - Fix places were DBUG_OFF is used
percona/percona-xtrabackup pull request #1087
Opened 2021-05-17 15:50 UTC by altmannmarcelo

https://jira.percona.com/browse/PXB-2500

Problem:
c3588e1 changed the terminology of debug capabilities from DBUG_OFF to NDEBUG.
Xtrabackup was still using it to validate if --debug=name would be
compiled.

Fix:
Adjust ifndef statement to reflect new terminology.

2021-05-17 15:51 UTC, altmannmarcelo commented
https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param/40/

No more issues with simulate_lower_version

2021-05-18 04:19 UTC, rahulmalik87 requested changes

2021-05-18 04:19 UTC, rahulmalik87 commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +#ifndef NDEBUG
can you replace other `#endif /* !DBUG_OFF */` with NDEBUG

2021-05-19 04:24 UTC, rahulmalik87 approved these changes
LGTM

2021-05-19 15:39 UTC, merged