Fixed PXB-2505 - Keyring is not generated properly by generate-new-ma…
percona/percona-xtrabackup pull request #1091
Opened 2021-05-21 10:55 UTC by altmannmarcelo

…ster-key for component

https://jira.percona.com/browse/PXB-2505

Problem:
Keyring operations use server uuid in order to prefix the master key
name. Component implementation of xtrabackup was missing read it from
backup-my.cnf when starting offline operations.

Fix:
Added required functions to read server-uuid from backup-my.cnf file.

2021-05-21 10:55 UTC, altmannmarcelo commented
https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param/45/

2021-05-21 12:21 UTC, satya-bodapati requested changes

2021-05-21 12:21 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/keyring_components.cc
> +}
Do we need this? Looks like we are not using it?

2021-05-21 12:21 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/keyring_components.cc
> +
can we refactor a bit. I see same code in load_backup_my_cnf() for a different option?

2021-05-25 11:21 UTC, altmannmarcelo commented
https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param/48/ - Test results after refactor.

2021-05-25 12:50 UTC, satya-bodapati approved these changes
@altmannmarcelo Didn't expect the refactor would cause so much extra work. Thank you for doing it!

2021-05-25 13:37 UTC, merged