PXB-2106 : copy-back creates wrong binlog.index
percona/percona-xtrabackup pull request #1094
Opened 2021-05-27 06:19 UTC by kennt-percona

PXB-2457 : Incorrect binlog names if binlog name contains periods

Issue
When performing copy-back, PXB will add incorrect file names to the binlog index.
This occurs when:
(1) an absolute path is used for the binlog and
(2) when the path is the datadir path.

Also, if the binlog name contains a period ('.'), we were not building
the binlog file names the same way as MySQL.

Solution
This occurs because the system treats the path as an absolute path
(because it is specified as an absolute path) and it treats it as
a relative path (because the path is in the datadir).
This exposed a bug in how we were parsing the paths.

Binlog names with a period ('.') are not generated the same way as MySQL.
Everything after the first '.' is removed.

2021-05-27 06:19 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1094) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1094) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtrabackup?pullRequest=1094) it.</sub>

2021-05-27 12:17 UTC, altmannmarcelo requested changes
A few inline comments plus:

* Is this 8.0 only? If not, please start with 2.4 path
* Can you please adjust the commit message to include the link to jira ticket, like https://github.com/percona/percona-xtrabackup/commit/80c1ba62aa65d9b0583ca2ad0eb21616b45264a2
* Can you please run jenkins against it. For PXB we use https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-multijob/ to trigger a compile + test tasks. After ready, please send us the link for your test param (https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param/)

2021-05-27 12:17 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +          r.name = r.name.substr(0, r.name.find(FN_EXTCHAR)) + suffix;
This same code is used in the else branch. Can we move `r.name` to before  `if (Fil_path::is_absolute_path(opt_log_bin)) {` and inside the if/else compute only `r.path`

2021-05-27 12:17 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +          r.name = r.name.substr(0, r.name.find(FN_EXTCHAR)) + suffix;
Move the declaration of `suffix` to this part of the code too.

2021-05-27 12:17 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +          r.path = std::string(buf).substr(0, dirname_length(buf)) + r.name;
Can you please let me know why this part is needed?
If understand correctly, the issue only happens if you have a full path that points to datadir. This else branch falls into the not absolute path.

2021-05-28 04:53 UTC, kennt-percona commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +          r.path = std::string(buf).substr(0, dirname_length(buf)) + r.name;
This is the other bug that was being fixed.  PXB-2457.

2021-05-28 09:12 UTC, kennt-percona commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +          r.name = r.name.substr(0, r.name.find(FN_EXTCHAR)) + suffix;
code moved

2021-05-28 09:23 UTC, kennt-percona commented
@altmannmarcelo 
This is 8.0 only.

2021-05-28 12:02 UTC, altmannmarcelo approved these changes
@kennt-percona Thanks for fixing my comments. LGTM

2021-05-29 03:55 UTC, merged

2021-07-30 08:53 UTC, Techshrimp commented
This is due to the fact that the binlog name is different before and after the backup and causes problems during parsing, which can be replicated normally, and is related to the target_location function.

from percona-xtrabackup-8.0.6 to percona-xtrabackup-8.0.23-16

binlog_file_location target_location(const std::string &datadir) const {
    binlog_file_location r;

    if (!name.empty()) {
      std::string suffix = fn_ext(name.c_str());

      if (opt_log_bin != nullptr) {
        if (Fil_path::is_absolute_path(opt_log_bin)) {
          r.name =
              std::string(opt_log_bin).substr(0, dirname_length(opt_log_bin)) +
              suffix;
          r.path = opt_log_bin + suffix;
        } else {
          char buf[FN_REFLEN];
          fn_format(buf, opt_log_bin, datadir.c_str(), "", MY_UNPACK_FILENAME);
          r.name = opt_log_bin + suffix;
          r.path = buf + suffix;
        }