PXB-2.4-1961 Prepare of full backup fails for encrypted tables with Gener…
percona/percona-xtrabackup pull request #1095
Opened 2021-05-28 07:46 UTC by rahulmalik87

…ic error

https://jira.percona.com/browse/PXB-1961

Problem:
PXB is not handling redo type generated by PS for encryption keyring

Analysis:
PS supports addition encryption types like keyring which is not handled
by PXB. This bugs only adresses encryption='n'

Fix:
Process KEY_MAGIC_PS generated by PS. also error out if redo log on page
0 found with CRYPT_SCHEME_1 that is keyring encryption is used

2021-05-28 08:25 UTC, rahulmalik87 commented
waiting for jenkin result https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium/170/ . will update results here

2021-05-28 09:55 UTC, satya-bodapati requested changes

2021-05-28 09:55 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +                        ptr_copy += 2;
use comment
// skip offset

Also, alignment seems wrong from the comment

2021-05-28 09:55 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +                                return NULL;
if (end_ptr < ptr_copy + len) {
                                return(NULL);
                   }

2021-05-28 09:55 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +			/* to only support encryption ='n' with PS */
Add a bit more detailed comment
/* Tables created with ENCRYPTION='N' have crypt_data (UNENCRYPTED SCHEM) in Page 0 */

2021-05-28 09:55 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +				// increase by  magic size, iv_len, space_id, offset,
say // skip magic_size, iv_len, space_id, offset to read the "type" in crypt_data

2021-05-28 09:55 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +				ptr_copy += 3 + 2  + 4 + 2 ;
better to use constants for these.
iv_len is 2 bytes?

2021-05-28 09:55 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +				if(type != CRYPT_SCHEME_UNENCRYPTED) {
if (

2021-05-28 09:55 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +						"KEYRING encrypion";
better to add  "<<" at start of every line (some compilers don't like this concatenation)

2021-05-28 09:55 UTC, satya-bodapati requested changes

2021-05-28 09:55 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +                        ulint len = mach_read_from_2(ptr_copy);
can you debug assert ut_ad(len == KEYRING_ENCRYPTION_SIZE)

2021-05-28 12:45 UTC, satya-bodapati requested changes

2021-05-28 12:45 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +                        ulint len = mach_read_from_2(ptr_copy);
This alignment still looks wrong to me. Please check your tabs vs spaces

2021-05-28 12:45 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +#ifdef XTRABACKUP
do we need the Ifdefs?

2021-05-28 12:45 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +			/* Tables created with ENCRYPTION='N' have crypt_data
With Percona Server, tables created ..

2021-05-28 12:45 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +			(UNENCRYPTED SCHEM) in Page 0 */
SCHEME

2021-05-28 12:45 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +				//skip space_id, offset to read the type in crypt data
// skip

2021-05-28 12:45 UTC, satya-bodapati commented on storage/innobase/xtrabackup/test/t/keyring_pxb_1961.sh
> +}
this seems very useful. Can you make it a bit generic by passing database as input parameter.

and move it to common.sh

2021-05-28 12:45 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +				ut_ad(len == encrypt_info_size);
this is fine,
I also want to compare with hard-coded numbers. (I belive only two lengths are possible)

2021-06-03 07:01 UTC, rahulmalik87 commented
jenkin results. https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium/176/

2021-06-03 13:07 UTC, satya-bodapati requested changes

2021-06-03 13:07 UTC, satya-bodapati commented on storage/innobase/xtrabackup/test/t/keyring_pxb_1961.sh
> +}
@rahulmalik87 can you please address this comment as well?

2021-06-03 13:09 UTC, satya-bodapati requested changes

2021-06-03 13:09 UTC, satya-bodapati commented on storage/innobase/xtrabackup/test/t/keyring_pxb_1961.sh
> +  run_cmd xtrabackup --backup --target-dir=$topdir/backup --xtrabackup-plugin-dir=${plugin_dir}
--xtrabackup-plugin-dir is necessary? :thinking:

2021-06-03 13:10 UTC, satya-bodapati commented on storage/innobase/xtrabackup/test/t/keyring_pxb_1961.sh
> +  run_cmd xtrabackup --backup --target-dir=$topdir/backup --xtrabackup-plugin-dir=${plugin_dir}
may be lets keep it. Useful or keyring plugin stuff I guess.

2021-06-03 13:11 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +			ENCRYPTION='N' have crypt_data (UNENCRYPTED SCHEMA)
it is just SCHEME

2021-06-04 07:38 UTC, satya-bodapati requested changes
patch looks good. can you please submit to Jenkins and update the link here?

2021-06-07 10:23 UTC, rahulmalik87 commented
> patch looks good. can you please submit to Jenkins and update the link here?

https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium/181/testReport/

2021-06-07 11:23 UTC, satya-bodapati requested changes
1. can you rename test to avoid numbers? (Please remember this. Applicable for all PRs)
may be keyring_encryption.sh ?
2. I see that the test is skipped on debug builds also.
https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium/181/BUILD_TYPE=debug,Host=min-centos-8-x64,xtrabackuptarget=innodb57/consoleFull

`keyring_pxb_1961                         w4	[skipped]   Require debug server version`

2021-06-07 11:55 UTC, rahulmalik87 commented
> 1. can you rename test to avoid numbers? (Please remember this. Applicable for all PRs)
>    may be keyring_encryption.sh ?
> 2. I see that the test is skipped on debug builds also.
>    https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium/181/BUILD_TYPE=debug,Host=min-centos-8-x64,xtrabackuptarget=innodb57/consoleFull
> 
> `keyring_pxb_1961 w4 [skipped] Require debug server version`

renamed the testcase, waiting for fix for PXB-2512. paste the manual result

{smm-12-d40aec x7 o7 xtrabackup-test}$./run.sh -t t/keyring_encryption.sh
Using /home/rahul.malik/MySQL/build/x7/xtrabackup-test/var as test root
Detecting server version...
Running against MySQL 5.7.34-debug-log (InnoDB 5.7.34)
Using 'xtrabackup' as xtrabackup binary
Using 8 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
n xp7
lnb
keyring_encryption                       w1	[skipped]   Requires XtraDB
==============================================================================
Spent 26 of 33 seconds executing testcases

SUMMARY: 1 run, 0 successful, 1 skipped, 0 failed

Skipped tests:  keyring_encryption

See results/ for detailed output
{smm-12-d40aec x7 o7 xtrabackup-test}$n xp7
{smm-12-d40aec x7 p7 xtrabackup-test}$lnb
{smm-12-d40aec x7 p7 xtrabackup-test}$./run.sh -t t/keyring_encryption.sh
Using /home/rahul.malik/MySQL/build/x7/xtrabackup-test/var as test root
Detecting server version...
Running against Percona Server 5.7.33-36-debug-log (XtraDB 5.7.33-36)
Using 'xtrabackup' as xtrabackup binary
Using 8 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
keyring_encryption                       w1	[passed]    28
==============================================================================
Spent 28 of 36 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output

2021-06-07 11:59 UTC, satya-bodapati approved these changes
LGTM!

2021-06-11 08:07 UTC, rahulmalik87 commented
./run.sh -t t/keyring_encryption.sh
Using /home/rahul.malik/MySQL/build/x7/xtrabackup-test/var as test root
Detecting server version...
Running against Percona Server 5.7.33-36-debug-log (XtraDB 5.7.33-36)
Using 'xtrabackup' as xtrabackup binary
Using 8 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
keyring_encryption                       w1	[passed]    29
==============================================================================
Spent 29 of 37 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output
{smm-12-d40aec x7 o7 xtrabackup-test}$

2021-06-11 08:22 UTC, satya-bodapati approved these changes

2021-06-11 08:22 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +                             (CRYPT_SCHEME_UNENCRYPTED) in Page 0 */
Please align the comment :)

2021-06-11 09:56 UTC, rahulmalik87 commented
./run.sh -t t/keyring_encryption.sh
Using /home/rahul.malik/MySQL/build/x7/xtrabackup-test/var as test root
Detecting server version...
Running against Percona Server 5.7.33-36-debug-log (XtraDB 5.7.33-36)
Using 'xtrabackup' as xtrabackup binary
Using 8 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
keyring_encryption                       w1	[passed]    35
==============================================================================
Spent 35 of 44 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output
{smm-12-d40aec x7 o7 xtrabackup-test}$

2021-06-11 10:07 UTC, satya-bodapati approved these changes

2021-06-11 10:18 UTC, merged