PXB-2570 Release notes for XtraBackup 8.0.26-18.0
percona/percona-xtrabackup pull request #1145
Opened 2021-08-05 14:46 UTC by nastena1606

new file: source/release-notes/8.0/8.0.26-18.0.rst
modified:   source/conf.py
	modified:   source/release-notes.rst

2021-08-05 16:06 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1145) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1145) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtrabackup?pullRequest=1145) it.</sub>

2021-08-26 14:37 UTC, patrickbirch reviewed
Date is still August 14

2021-08-26 14:37 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +:Date: August 14, 2021
Date is wrong.

2021-08-26 14:39 UTC, nastena1606 commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +:Date: August 14, 2021
Thanks. Fixed

2021-08-26 14:43 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2585`: XtraBackup fails to backup archive rockdb wal files
RocksDB Write-Ahead Log (WAL) files

2021-08-26 14:46 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2477`: xbcloud should retry on error and utilize incremental backoff (Thanks to Baptiste Mille-Mathias for reporting this issue)
The xbcloud binary should retry on an error and utilize an incremental backoff

2021-08-26 14:50 UTC, altmannmarcelo requested changes

2021-08-26 14:50 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2580`: xbcloud: retry chunk-upload upon receiving the ``SSL connect`` error
Add thanks to Tim Vaillancourt for providing the patch

2021-08-26 14:50 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2554`: Add the logic to skip tests if XtraBackup was compiled under ASAN
remove it

2021-08-26 14:50 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2551`: Fix ``gr_basic`` test to stop on timeout in innodb80
remove

2021-08-26 14:50 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2585`: XtraBackup fails to backup archive rockdb wal files
This was found out by a forum user. I'm waiting to get his name so we can credit him.

2021-08-26 14:55 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2580`: xbcloud: retry chunk-upload upon receiving the ``SSL connect`` error
With the xbcloud binary, a chunk-upload on an SSL connect error to S3 was not retried.

2021-08-26 15:07 UTC, nastena1606 commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2551`: Fix ``gr_basic`` test to stop on timeout in innodb80
Removed

2021-08-26 15:07 UTC, nastena1606 commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2554`: Add the logic to skip tests if XtraBackup was compiled under ASAN
Removed

2021-08-26 15:08 UTC, nastena1606 commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2580`: xbcloud: retry chunk-upload upon receiving the ``SSL connect`` error
Fixed

2021-08-26 15:08 UTC, nastena1606 commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2580`: xbcloud: retry chunk-upload upon receiving the ``SSL connect`` error
Added

2021-08-26 15:08 UTC, nastena1606 commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2477`: xbcloud should retry on error and utilize incremental backoff (Thanks to Baptiste Mille-Mathias for reporting this issue)
Amended

2021-08-26 15:20 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2317`: Remove LOCKLESS binlog functionality
Remove the LOCKLESS binary log functionality

2021-08-26 15:24 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2101`: The Prepare step fails due to duplicate sdi (Thanks to Fungo Wang for reporting this issue)
Serialized Dictionary Information (SDI)

2021-08-30 10:45 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2317`: Remove the LOCKLESS binlog functionality
binary log instead of binlog.

2021-08-30 10:46 UTC, patrickbirch approved these changes
LGTM

2021-08-30 14:09 UTC, georgelorchpercona approved these changes

2021-08-30 19:07 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2585`: XtraBackup fails to backup archive rockdb wal files
didn't get a reply on time :( . Let's proceed without the credits.

2021-08-30 19:07 UTC, altmannmarcelo approved these changes
LGTM

2021-09-01 12:16 UTC, nastena1606 commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2317`: Remove the LOCKLESS binlog functionality
Fixed

2021-09-01 13:03 UTC, mchawla16 approved these changes
Remove PXB-2526, if it's an internal issue and not impacting a customer

2021-09-01 13:36 UTC, nastena1606 commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.26-18.0.rst
> +* :jirabug:`PXB-2317`: Remove LOCKLESS binlog functionality
Fixed

2021-09-02 15:28 UTC, merged