Fixed PXB-2594 - kill-long-queries-timeout segmentation fault.
percona/percona-xtrabackup pull request #1157
Opened 2021-08-26 21:41 UTC by altmannmarcelo

https://jira.percona.com/browse/PXB-2594

Problem:
When we call stop_query_killer we set kill_query_thread_stop event
which tells the kill_query_thread it should start its stop_thread
routine. As part of this routine, it will call my_thread_end and then
set kill_query_thread_stopped event. On the main thread where we are
executing stop_query_killer, we will wait 60ms for
kill_query_thread_stopped event to be set and then continue the routine
that deletes the os_events created to add syncronization to
kill_query_thread. In case my_thread_end called from kill_query_thread
takes more than 60ms the main thread will continue its workflow and
destroy kill_query_thread_stopped event. Later when kill_query_thread
completes my_thread_end it will try to set kill_query_thread_stopped
but the event is already destroyed.

Fix:
Adjust main thread to keep waiting for kill_query_thread_stopped to be
set before destroying the event.

2021-08-26 21:41 UTC, altmannmarcelo commented
https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param/108/

2021-08-27 08:19 UTC, satya-bodapati requested changes

2021-08-27 08:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +  }
we dont need loop right? just simple event wait should do.  os_event_wait(kill_query_thread_stop)?

2021-08-27 11:00 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +  }
good point. Adjusting it.

2021-08-27 11:14 UTC, satya-bodapati approved these changes

2021-08-27 11:54 UTC, merged