PXB-2603 Release Notes for 2.4.24 (2.4)
percona/percona-xtrabackup pull request #1170
Opened 2021-09-06 17:06 UTC by patrickbirch

Modified files:
conf.py
release-notes
Added file:
2.4.24

2021-09-07 16:08 UTC, altmannmarcelo requested changes

2021-09-07 16:08 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.24.rst
> +* :jirabug:`PXB-2580`: xbcloud: a chunk-upload on SSL connect error to Amazon S3 was not retried.
Please add the credits as per 8.0 RN

2021-09-07 16:08 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.24.rst
> +* :jirabug:`PXB-1504`: FIND_GCRYPT macro is broken
Same here.

2021-09-07 17:43 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.24.rst
> +* :jirabug:`PXB-2580`: xbcloud: a chunk-upload on SSL connect error to Amazon S3 was not retried.
Added.

2021-09-07 17:44 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.24.rst
> +* :jirabug:`PXB-1504`: FIND_GCRYPT macro is broken
Added.

2021-09-07 18:34 UTC, altmannmarcelo approved these changes

2021-09-10 14:06 UTC, mchawla16 approved these changes

2021-09-14 14:18 UTC, merged