PXB-2614 Followup-fix xbstream sparse files support doesn't work on XFS
percona/percona-xtrabackup pull request #1192
Opened 2021-10-28 07:00 UTC by rahulmalik87

https://jira.percona.com/browse/PXB-2614

fixed the compilation error on macos

2021-10-28 11:50 UTC, altmannmarcelo requested changes
few minor comments.

Also, please send a jenkins test run.

2021-10-28 11:50 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/ds_local.cc
> +    return;
we should not have a return on a void function.

2021-10-28 11:50 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/ds_local.cc
> +#endif
```suggestion
#else
  ctxt->fs_support_punch_hole = false;
#endif
```

2021-10-28 11:50 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/ds_local.cc
> +#ifdef HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE
just wondering if this can cause warnings because `punch_hole_supported` is not used in the function?

2021-11-09 10:37 UTC, rahulmalik87 commented on storage/innobase/xtrabackup/src/ds_local.cc
> +#ifdef HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE
variables FALLOC_FL_PUNCH_HOLE and FALLOC_FL_KEEP_SIZE is not defined in macos.

2021-11-09 10:44 UTC, rahulmalik87 commented on storage/innobase/xtrabackup/src/ds_local.cc
> +    return;
fixed

2021-11-09 10:44 UTC, rahulmalik87 commented on storage/innobase/xtrabackup/src/ds_local.cc
> +#endif
fixed

2021-11-09 14:40 UTC, rahulmalik87 commented
jenkin results, https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param/134/testReport/

2021-11-25 11:24 UTC, altmannmarcelo requested changes

2021-11-25 11:24 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/ds_local.cc
> +#ifdef HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE
What I mean is that on function signature we have a parameter `punch_hole_supported` however on macos, due to preprocessor `HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE` we will never use it. I would prefer that we also extend the `#ifdef HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE` to function signature. Something like:

```
static int local_write_sparse(ds_file_t *file, const void *buf, size_t len,
                              size_t sparse_map_size,
                              const ds_sparse_chunk_t *sparse_map
#ifdef HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE
                              , bool punch_hole_supported
#endif
){

```

2021-11-25 12:30 UTC, rahulmalik87 commented on storage/innobase/xtrabackup/src/ds_local.cc
> +#ifdef HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE
now using  __attribute__((unused))

2021-11-25 13:52 UTC, altmannmarcelo requested changes
@rahulmalik87 thanks for your suggestion regarding the unused attribute.
Last request - can you use `[[maybe_unused]]` instead?

2021-11-29 12:59 UTC, rahulmalik87 commented
> maybe_unused

Thanks for suggestion . Using maybe_unused now.

2021-11-29 13:14 UTC, altmannmarcelo approved these changes
LGTM

2021-11-30 08:45 UTC, merged