PXB-2633 Update Encrypted Tablespace backups (2.4)
percona/percona-xtrabackup pull request #1196
Opened 2021-11-09 18:23 UTC by patrickbirch

modified:   source/advanced/encrypted_innodb_tablespace_backups.rst

2021-12-27 13:12 UTC, altmannmarcelo requested changes

2021-12-27 13:12 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/advanced/encrypted_innodb_tablespace_backups.rst
> +   --transition-key=MySecretKey
```suggestion
   $ xtrabackup --prepare --target-dir=/data/backup \
   --transition-key=MySecretKey
```

2021-12-27 16:26 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/advanced/encrypted_innodb_tablespace_backups.rst
> +   --transition-key=MySecretKey
Fixed.

2022-01-12 12:38 UTC, altmannmarcelo approved these changes
LGTM

2022-01-12 12:44 UTC, merged