PXB-2668 Return the exit code for each pipe when using xbcloud (2.4)
percona/percona-xtrabackup pull request #1225
Opened 2021-12-20 18:48 UTC by patrickbirch

modified: source/xbcloud/xbcloud.rst

2021-12-27 13:01 UTC, altmannmarcelo requested changes

2021-12-27 13:01 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/xbcloud/xbcloud.rst
> +   In a Bash shell, the ``$?`` parameter returns the exit code from the last binary. If you use pipes, the ``${PIPESTATUS[x]}`` array parameter returns the exit codes for each binary in the pipe stri
could we add an example here:

```
If you use pipes like ``xtrabackup [options] | xbcloud [option]``, the ``${PIPESTATUS[x]}`` array parameter ...

2021-12-27 16:21 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/xbcloud/xbcloud.rst
> +   In a Bash shell, the ``$?`` parameter returns the exit code from the last binary. If you use pipes, the ``${PIPESTATUS[x]}`` array parameter returns the exit codes for each binary in the pipe stri
Added to the example code

2022-01-13 12:05 UTC, altmannmarcelo requested changes

2022-01-13 12:05 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/xbcloud/xbcloud.rst
> +      0 0
```suggestion
> true | false
> echo $?
> 1

# With PIPESTATUS
> true | false
> echo ${PIPESTATUS[0]} ${PIPESTATUS[1]}
> 0 1

```

2022-02-16 21:21 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/xbcloud/xbcloud.rst
> +      0 0
Added.

2022-02-17 12:24 UTC, altmannmarcelo approved these changes

2022-02-17 12:46 UTC, merged