PXB-2706 encrypt-key example key is too short for AES256 (8.0)
percona/percona-xtrabackup pull request #1260
Opened 2022-02-14 14:44 UTC by patrickbirch

M source/xtrabackup_bin/backup.encrypting.rst

2022-02-14 16:06 UTC, alina-derkach-oaza approved these changes

2022-02-15 08:49 UTC, rahulmalik87 requested changes

2022-02-15 08:49 UTC, rahulmalik87 commented on storage/innobase/xtrabackup/doc/source/xtrabackup_bin/backup.encrypting.rst
the command should be openssl rand -base64 32

2022-02-15 11:38 UTC, altmannmarcelo approved these changes
LGTM after addressing @rahulmalik87 request.

2022-02-15 11:39 UTC, altmannmarcelo commented
Does it apply to 2.4 documentation too ?

2022-02-15 13:24 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/xtrabackup_bin/backup.encrypting.rst
Changed from 32

2022-02-15 14:04 UTC, rahulmalik87 commented
LGTM.

2022-02-15 14:51 UTC, patrickbirch commented
This change does not apply to 2.4.

2022-02-15 16:20 UTC, merged