Fixed HD-1549 validate decompression path
percona/percona-xtrabackup pull request #1263
Opened 2022-02-22 18:07 UTC by altmannmarcelo

Problem:
While decompressing a backup, we pass filepath and dest_filepath to
system call without any validation.

Fix:
Quote those path's in order to make it more secure.

2022-02-23 08:09 UTC, rahulmalik87 approved these changes
LGTM

2022-02-23 12:30 UTC, satya-bodapati commented on storage/innobase/include/xb0xb.h
> +#define SQUOTE(str) "'" << str << "'"
Looks familiar :D

2022-02-23 12:30 UTC, satya-bodapati approved these changes

2022-02-23 15:17 UTC, altmannmarcelo commented on storage/innobase/include/xb0xb.h
> +#define SQUOTE(str) "'" << str << "'"
that is called backporting :D

2022-02-28 12:39 UTC, Oneiroi requested changes
Please refer to the associated ticket that spawned this PR, the fix is noted as incomplete at this stage and needs further refinement to meet the intended purpose.

2022-03-01 13:10 UTC, Oneiroi approved these changes
Please see my notes on `FN_LEN`, right now this LGTM though I am also aware that my COVID brain may be causing me to miss something so to err on the side of caution, I will request validation from stakeholders and communicate their comments via the HD ticket, thanks :+1:

2022-03-01 13:10 UTC, Oneiroi commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +	char buf[FN_LEN];
Where is `FN_LEN` being defined ? 

I note this is present in https://github.com/percona/percona-xtrabackup/blob/da04f2363f6ed1f601a690cc56856131c6d574b8/include/my_io.h#L79 however this is not being included in this file, I've missed or am unable to identify where FN_LEN is being set (this is set as `256` in the my_io.h header file fwiw)

2022-03-01 13:10 UTC, Oneiroi commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +	if (escape_string_for_mysql(&my_charset_utf8_general_ci, buf, 0,
I presume this is the function that's being called here: https://github.com/percona/percona-xtrabackup/blob/d4cbe0e6d4b4895dda372353f3abab23aa17c96a/mysys/charset.cc#L733-L833

This is pretty exhaustive and even escapes multibyte chars afaict (read: this _may_ also intercept the use of unicode homoglyph's in filenames also). 👍

2022-03-01 13:13 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +	char buf[FN_LEN];
backup_copy.cc -> #include xtrabackup.h -> #include xbstream.h -> #include <my_io.h>

2022-03-01 13:17 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +	if (escape_string_for_mysql(&my_charset_utf8_general_ci, buf, 0,
correct, also in that sense we might better use `my_charset_utf8mb4_general_ci` instead so we are covered on the 4th byte too.

2022-03-15 13:34 UTC, closed without merging