PXB-2749 Create 2.4.25 release notes and release note tasks
percona/percona-xtrabackup pull request #1304
Opened 2022-04-21 11:41 UTC by alina-derkach-oaza

new file: storage/innobase/xtrabackup/doc/source/_res/replace/pxb-blurb.txt
new file: storage/innobase/xtrabackup/doc/source/_res/replace/useful-links.txt
modified: storage/innobase/xtrabackup/doc/source/conf.py
modified: storage/innobase/xtrabackup/doc/source/release-notes.rst
new file: storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.25.rst

2022-04-21 11:43 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1304) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1304) before we can accept your contribution.<br/><hr/>**“Alina** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtrabackup?pullRequest=1304) it.</sub>

2022-04-25 12:47 UTC, patrickbirch approved these changes

2022-04-25 14:51 UTC, georgelorchpercona approved these changes
+1

2022-04-25 14:59 UTC, altmannmarcelo requested changes
just a small change to put Ivan's full name on the thanks section.

2022-04-25 14:59 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.25.rst
> +* :jirabug:`PXB-1883`: Implements support for Microsoft Azure Cloud Storage in the xbcloud binary. (Thanks to Ivan for reporting this issue)
```suggestion
* :jirabug:`PXB-1883`: Implements support for Microsoft Azure Cloud Storage in the xbcloud binary. (Thanks to Ivan Groenewold for reporting this issue)
```

2022-04-25 15:14 UTC, alina-derkach-oaza commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.25.rst
> +* :jirabug:`PXB-1883`: Implements support for Microsoft Azure Cloud Storage in the xbcloud binary. (Thanks to Ivan for reporting this issue)
Fixed

2022-04-25 15:18 UTC, altmannmarcelo approved these changes
LGTM

2022-04-26 13:24 UTC, merged