PXB-2781 Create release notes and release note tasks for 8.0.29-21
percona/percona-xtrabackup pull request #1333
Opened 2022-05-19 13:35 UTC by alina-derkach-oaza

modified: source/conf.py
modified: source/release-notes.rst
new file: source/release-notes/8.0/8.0.29-21.0.rst

2022-05-19 13:35 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1333) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1333) before we can accept your contribution.<br/><hr/>**Alina Derkach** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtrabackup?pullRequest=1333) it.</sub>

2022-05-19 15:25 UTC, altmannmarcelo requested changes

2022-05-19 15:25 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/conf.py
> +release = '8.0.29-21.0'
the release number is 8.0.28-21

2022-05-19 15:37 UTC, alina-derkach-oaza commented on storage/innobase/xtrabackup/doc/source/conf.py
> +release = '8.0.29-21.0'
Fixed

2022-05-24 10:39 UTC, patrickbirch approved these changes
LGTM

2022-05-24 14:41 UTC, georgelorchpercona approved these changes

2022-05-25 13:00 UTC, mchawla16 approved these changes

2022-05-25 13:23 UTC, merged