PXB-2759 regression on check_for_passwords.sh
percona/percona-xtrabackup pull request #1340
Opened 2022-05-30 06:52 UTC by rahulmalik87

https://jira.percona.com/browse/PXB-2759

added sleep 3 befor checking output of ps

2022-05-30 11:44 UTC, rahulmalik87 commented
jenkin results https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-multijob/182

2022-06-01 04:42 UTC, rahulmalik87 commented
jenkin results. https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param/201/

2022-06-01 14:26 UTC, satya-bodapati approved these changes
Please squash before the merge

2022-06-02 19:03 UTC, altmannmarcelo requested changes
@rahulmalik87 although the suggested change might work, I would investigate why this is failing without the debug sync.
Based on your changes, the issue comes from `decrypting` part. I would enhance debugging there to validate why it fails, Having the `decrypting` string on pxb output log should be enough to be passed the argument handling part, which should be stripping sensitive information.

2022-06-02 19:03 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +  debug_sync_point("decrypt_decompress_func");
Do we really need this one? checking for `decrypt` isn't enough?

2022-06-02 19:03 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/test/t/check_for_passwords_debug.sh
> +       2> >( tee $topdir/decompress.log)&
decrypt.log

2022-06-02 19:03 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/test/t/check_for_passwords.sh
> -       2> >( tee $topdir/pxb_2740.log)&
I would leave this part with extra information to validate why this is failing.

2022-06-03 04:07 UTC, rahulmalik87 commented
> @rahulmalik87 although the suggested change might work, I would investigate why this is failing without the debug sync.
> Based on your changes, the issue comes from `decrypting` part. I would enhance debugging there to validate why it fails, Having the `decrypting` string on pxb output log should be enough to be passed the argument handling part, which should be stripping sensitive information.

It fails because we don't have any mechanism to ensure decrypting is not finished at the time we are running ps command.
  
Having the `decrypting` string is enough but how we would ensure that decrypting is still running. That's why I thought to run only debug test case to 100% process would be running by the time we run ps -ef

2022-06-03 04:07 UTC, rahulmalik87 commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +  debug_sync_point("decrypt_decompress_func");
yeah, It is ensure the decrypting is not complete.

2022-06-03 04:09 UTC, rahulmalik87 commented on storage/innobase/xtrabackup/test/t/check_for_passwords_debug.sh
> +       2> >( tee $topdir/decompress.log)&
fixed

2022-06-03 04:10 UTC, rahulmalik87 commented on storage/innobase/xtrabackup/test/t/check_for_passwords.sh
> -       2> >( tee $topdir/pxb_2740.log)&
I can't find a way to ensure the process would be blocked untill we run ps

2022-06-16 12:17 UTC, altmannmarcelo approved these changes
LGTM

2022-06-22 08:24 UTC, merged