PXB-2865 Failed to copy dymainc metadata
percona/percona-xtrabackup pull request #1429
Opened 2023-03-01 08:50 UTC by rahulmalik87

https://jira.percona.com/browse/PXB-2865

We have the logic of skipping dynamic metadata on the apply-log phase and relying on MySQL.ibd to copy those changes. see PXB-2180 The issue comes if there are change that are not flushed to mysql.ibd before the Final incremental backup.
Final Incremental prepare will skip applying of DYNAMIC_METADATA redo and mysql.ibd will not have those changes.

PXB does not allow final prepare on backup prepared already with apply-log-only. Last incremental backup should be prepared without apply-log-only.

2023-03-01 11:31 UTC, satya-bodapati requested changes

2023-03-01 11:31 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +                   "--apply-log-only";
I don't understand the intention of the second part of the message "or if you restoring.."

2023-03-01 11:31 UTC, satya-bodapati commented on storage/innobase/xtrabackup/test/suites/keyring/innodb_encryption_export.sh
> +${XB_BIN} --prepare --incremental-dir=$topdir/inc2 \
is it possible to combine these two steps? (Just asking. Not asking you to change yet :))

2023-03-01 11:31 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +                   "--apply-log-only";
PXB-2180 is fixed in 8.0.23. Is it possible to reproduce these assertions using PXB 8.0.23? (with the disable page cleaner patch)?

2023-03-10 14:30 UTC, altmannmarcelo requested changes
I would rather work on a final solution rather than silent test cases

2023-07-31 20:10 UTC, altmannmarcelo commented
Closing. Once this is implemented, it will be done as a new PR.

2023-07-31 20:10 UTC, closed without merging