PXB-2972 : InnoDB: Assertion failure: log0log.cc:1627:srv_is_being_st…
percona/percona-xtrabackup pull request #1432
Opened 2023-03-03 12:08 UTC by satya-bodapati

…arted || srv_shutdown_state.load() == SRV_SHUTDOWN_EXIT_THREADS

Problem:
--------
When PXB errors out after applying redo, i.e. when we are booting InnoDB to load tables to do rollback, an error at this stage causes PXB to crash instead of a graceful exit.

PXB renames the xtrabackup_logfile to 'ib_redo0' file to apply redo and later on errors (or on success too).
On success (and if PXB hasn't generated any new redo files) and on errors, we rename back the ib_redo0 to xtrabackup_logfile

To check if any new redo files are created, PXB checks the state of redo files.

At this stage, InnoDB is de-initialized and the InnoDB APIs accessing the redo files do not expect the state to be in SRV_SHUTDOWN_NONE.

Fix:
----
Relax the assertion to make PXB exit gracefully

2023-03-03 12:44 UTC, satya-bodapati commented
https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-multijob/260/

2023-03-07 17:32 UTC, altmannmarcelo requested changes
@satya-bodapati my only concern here is that we might be allowing pxb to initialize the log
_sys twice. We should not do it, but if we erroneously do so, the assertion will prevent that.
Is it possible for us to change the srv_shutdown_state in case of failure at dd boot?

2023-03-07 17:32 UTC, altmannmarcelo commented on storage/innobase/log/log0log.cc
> +
#ifdef XTRABACKUP

2023-03-07 17:32 UTC, altmannmarcelo commented on storage/innobase/log/log0log.cc
> +         srv_shutdown_state.load() == SRV_SHUTDOWN_EXIT_THREADS ||
```suggestion
         srv_shutdown_state.load() == SRV_SHUTDOWN_EXIT_THREADS IF_XB(||...
```

2023-03-08 12:15 UTC, satya-bodapati commented
> @satya-bodapati my only concern here is that we might be allowing pxb to initialize the log _sys twice. We should not do it, but if we erroneously do so, the assertion will prevent that. Is it possible for us to change the srv_shutdown_state in case of failure at dd boot?
@altmannmarcelo 
this is a good question. but the most interesting part it is it has nothing to do with "log_sys_init()"

In fact, the assertion puzzled me. Why would you call log_sys_int() on redo log IO read? Isn't it surprising?

2023-03-08 12:22 UTC, satya-bodapati commented
> > @satya-bodapati my only concern here is that we might be allowing pxb to initialize the log _sys twice. We should not do it, but if we erroneously do so, the assertion will prevent that. Is it possible for us to change the srv_shutdown_state in case of failure at dd boot?
> > @altmannmarcelo
> > this is a good question. but the most interesting part it is it has nothing to do with "log_sys_init()"
> 
> In fact, the assertion puzzled me. Why would you call log_sys_int() on redo log IO read? Isn't it surprising?

Answer is, these are callbacks that registered on IO read and write but the callbacks are defined in log_sys_init()

2023-03-08 15:03 UTC, satya-bodapati commented
> > > @satya-bodapati my only concern here is that we might be allowing pxb to initialize the log _sys twice. We should not do it, but if we erroneously do so, the assertion will prevent that. Is it possible for us to change the srv_shutdown_state in case of failure at dd boot?
> > > @altmannmarcelo
> > > this is a good question. but the most interesting part it is it has nothing to do with "log_sys_init()"
> > 
> > 
> > In fact, the assertion puzzled me. Why would you call log_sys_int() on redo log IO read? Isn't it surprising?
> 
> Answer is, these are callbacks that registered on IO read and write but the callbacks are defined in log_sys_init()

I've updated the comment in the code. It is just that, if an error occurs too early in innodb initialization, innodb is not considered inited. We have not created innodb threads yet.

An exit at this stage, wouldn't call innodb_end() and so srv_shutdown_state remains NONE.

2023-03-08 22:51 UTC, altmannmarcelo approved these changes
LGTM. Please squash before merging

2023-03-09 17:01 UTC, merged