PXB-3026 Turn OFF NDB storage engine compilation
percona/percona-xtrabackup pull request #1439
Opened 2023-03-28 06:25 UTC by rahulmalik87

Problem:
Upstream, from 8.0.31 added a new flag -DWITH_NDB_CLUSTER_STORAGE_ENGINE and  made it ON by default. The existing flag, -DWITH_NDB=OFF doesn't turn off the DWITH_NDB_CLUSTER_STORAGE_ENGINE to OFF and compiles NDB files

Fix:
SET WITH_NDB_CLUSTER_STORAGE_ENGINE explicitly off in PXB

2023-03-28 12:27 UTC, altmannmarcelo requested changes

2023-03-28 12:27 UTC, altmannmarcelo commented on CMakeLists.txt
> +  OPTION(WITH_NDBCLUSTER_STORAGE_ENGINE "Disable NDB for PXB" OFF)
Wouldn't it make more sense to add this where we declare WITH_NDBCLUSTER_STORAGE_ENGINE at storage/ndb/CMakeLists.txt ?

2023-03-28 13:18 UTC, rahulmalik87 commented on CMakeLists.txt
> +  OPTION(WITH_NDBCLUSTER_STORAGE_ENGINE "Disable NDB for PXB" OFF)
WITH_NDBCLUSTER_STORAGE_ENGINE is not declare in storage/ndb/CMakeList.txt. It is only used there.

2023-03-28 13:54 UTC, altmannmarcelo commented on CMakeLists.txt
> +  OPTION(WITH_NDBCLUSTER_STORAGE_ENGINE "Disable NDB for PXB" OFF)
I think it makes more sense to keep them together.

2023-03-29 08:47 UTC, rahulmalik87 commented on CMakeLists.txt
> +  OPTION(WITH_NDBCLUSTER_STORAGE_ENGINE "Disable NDB for PXB" OFF)
fixed

2023-03-29 08:48 UTC, rahulmalik87 commented
Now build directory contains only 

```
./storage/ndb
./sql/CMakeFiles/sql_dd.dir/dd/ndbinfo_schema
```

2023-04-03 10:11 UTC, satya-bodapati approved these changes
Can you please paste the compilation log?

2023-04-03 23:57 UTC, rahulmalik87 commented
> Can you please paste the compilation log?

[2000/2420] Building CXX object sql/CMakeFiles/sql_dd.dir/dd/ndbinfo_schema/init.cc.o

2023-04-03 23:59 UTC, rahulmalik87 commented
> Can you please paste the compilation log? 

//Disable NDB for PXB
WITH_NDBCLUSTER_STORAGE_ENGINE:BOOL=OFF

2023-04-03 23:59 UTC, merged