PXB-3139: Fix gcc-13 and clang-16 compilation issues
percona/percona-xtrabackup pull request #1493
Opened 2023-09-07 19:46 UTC by inikep

Fix the following issues:
1.
```
/data/percona-xtrabackup/8.0/storage/innobase/xtrabackup/src/keyring_plugins.cc:191:35: error: 'sizeof (TRANSITION_KEY_PREFIX)' will return the size of the pointer, not the array itself [-Werror,-Wsizeof-pointer-div]
    sizeof(TRANSITION_KEY_PREFIX) / sizeof(char);
```
2.
```
/data/percona-xtrabackup/8.0/storage/innobase/xtrabackup/src/backup_copy.cc:440:74: error: array index -1 is before the beginning of the array [-Werror,-Warray-bounds]
  data_threads = (datadir_thread_ctxt_t *)(ut::malloc_withkey(UT_NEW_THIS_FILE_PSI_KEY, length));
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~
/data/percona-xtrabackup/8.0/storage/innobase/include/ut0new.h:566:34: note: expanded from macro 'UT_NEW_THIS_FILE_PSI_KEY'
       : ut::make_psi_memory_key(auto_event_keys[UT_NEW_THIS_FILE_PSI_INDEX]))
                                 ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/percona-xtrabackup/8.0/storage/innobase/include/ut0new.h:447:1: note: array 'auto_event_keys' declared here
extern PSI_memory_key auto_event_keys[n_auto];
```

2023-09-07 19:46 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1493) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=1493) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtrabackup?pullRequest=1493) it.</sub>

2023-09-08 11:38 UTC, altmannmarcelo requested changes
@inikep thanks for fixing those. A couple of things

1. By looking into the commit, feels like you are fixing more than what is just described in the commit. can you please amend that and describe the failures (like rapidxml and xbcloud)
2. The vault/keyring we normally cherry-pick the corresponding commit from Percona Server, this way we can keep track / correlate what has been incorporated. You can do it in multiple commits if you want.
3. Jenkins is done at https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-multijob/

2023-09-08 12:41 UTC, inikep commented
I ported vault/keyring we fixes from Percona Server 8.0.34.
I started https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-multijob/301/

2023-09-11 12:30 UTC, altmannmarcelo requested changes
minor comments

2023-09-11 12:30 UTC, altmannmarcelo commented on storage/innobase/include/ut0new.h
> +    /* added for Percona XtraBackup */
```suggestion
#ifdef XTRABACKUP
```

2023-09-11 12:30 UTC, altmannmarcelo commented on storage/innobase/include/ut0new.h
> +    /* added for Percona XtraBackup */
PXB uses its own macro to shared code with server

2023-09-11 12:30 UTC, altmannmarcelo commented on plugin/keyring/common/system_keys_container.h
> +  ~System_keys_container() override;
Would you happen to know why neither PS nor upstream has this file?
This is not a PXB-specific code.

2023-09-11 12:30 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/xbcloud/xbcloud.cc
> +            [&thread_state](bool success, const Http_buffer &contents,
Good catch, we are passing ctx.error as pointer.

2023-09-11 12:53 UTC, inikep commented on plugin/keyring/common/system_keys_container.h
> +  ~System_keys_container() override;
`plugin/keyring/common/system_keys_container.h` was removed at https://github.com/percona/percona-server/pull/4954/files

2023-09-11 12:58 UTC, inikep commented on storage/innobase/include/ut0new.h
> +    /* added for Percona XtraBackup */
Fixed

2023-09-11 15:38 UTC, altmannmarcelo approved these changes
LGTM

2023-09-11 17:16 UTC, merged