Parallel extraction for xbstream
percona/percona-xtrabackup pull request #337
Opened 2017-03-21 06:47 UTC by gl-sergei

This patch added `--parallel=N` option for `xbstream`. When
specified, N worker threads are created, each reading next chunk from
input stream and writing it to destination file. While reading from
input stream is serialized, writing in two different files can be
done it parallel, which allows to squeeze maximum out of SSD/HDD
given that input pipe is fast enough.

2017-03-27 12:20 UTC, VasilyNemkov requested changes
There are minor issues with memory and resource leaks, please fix those.

2017-03-27 12:20 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/src/xbstream.c
> +		return 1;
Memory allocated for `tids` and `retvals` leaks, other stuff leaks too: `mutex` and `stream`.

2017-03-27 12:20 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/src/xbstream.c
>  		goto err;
`tids` and `retvals` leak here.

2017-03-27 12:20 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/src/xbstream.c
> +			goto err;
`tids` and `retvals` leak here.

2017-03-27 16:45 UTC, gl-sergei commented
Fixed

2017-03-28 09:31 UTC, VasilyNemkov approved these changes
Looks good

2017-03-28 09:31 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/src/xbstream_read.c
>  	F_READ(tmpbuf, 4);
Previous blocks followed pattern:
```
read
process
update_offset
```
but not this time, it looks like `stream->offset` is not updated here.

2017-03-28 09:31 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/src/xbstream_read.c
>  	F_READ(tmpbuf, 4);
Ah, it looks like offset is updated below
```
stream->offset += 4;
```

2017-03-28 09:58 UTC, merged