Bug 1551634: xtrabackup --slave-info does not handle multi-master replication
percona/percona-xtrabackup pull request #362
Opened 2017-04-26 13:37 UTC by VasilyNemkov

Writing master info for every channel to xtrabackup_slave_info;
Added a test case that verifies multi-source replication for both binlog and gtid mode.

https://bugs.launchpad.net/percona-xtrabackup/+bug/1551634

2017-04-26 14:27 UTC, VasilyNemkov commented
Param-build: http://jenkins.percona.com/view/PXB%202.3/job/percona-xtrabackup-2.4-param/185/

2017-04-26 21:47 UTC, gl-sergei requested changes
Please address test regressions as well.

2017-04-26 21:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +free_and_zero_mysql_variables(mysql_variable *vars)
Why add new function instead of making free_mysql_variables to zero values?

2017-04-26 21:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	//	read_mysql_variables(connection, "SHOW SLAVE STATUS", status, false);
Please remove this line

2017-04-26 21:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +		false) && ++masters_count) {
Incrementing counter inside of the loop body looks more straightforward to me

2017-04-26 21:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +		if (mysql_slave_position) {
Probably C++ strings will be easier to use and I see no reason not to...

2017-04-26 21:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +			ut_a(asprintf(&tmp_mysql_slave_position,
Maybe include channel_name as well?

2017-04-26 21:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +			ut_a(asprintf(&tmp_mysql_slave_position,
Maybe include channel_name as well?

2017-04-26 21:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/test/inc/common.sh
> +  FOR CHANNEL 'master-$master_id_arg';
This won't work on older servers, we need to make sure they are treated well

2017-04-26 21:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/test/t/bug1551634.sh
> +    innobackupex --no-timestamp --slave-info --safe-slave-backup $topdir/backup
Lets replace with xtrabackup. innobackupex is deprecated and should be removed in future major releases.

2017-04-26 21:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/test/t/bug1551634.sh
> +        --master-info-repository=TABLE \
Why do we need to set master-info-repository and relay-info-repository for this test?

2017-04-28 05:43 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/test/t/bug1551634.sh
> +        --master-info-repository=TABLE \
That is required to have multiple channels on slave. If we start slave server without both         `--master-info-repository=TABLE` and `--relay-log-info-repository=TABLE \`, then setting up server as slave with `CHANGE MASTER ... FOR CHANNEL '...'` fails with:
`ERROR 3077 (HY000) at line 1: To have multiple channels, repository cannot be of type FILE; Please check the repository configuration and convert them to TABLE.`

2017-04-28 13:30 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/test/inc/common.sh
> +  FOR CHANNEL 'master-$master_id_arg';
Fixed, now one have to explicitly specify `USE_CHANNELS` as an argument to the `setup_slave` in order to get named channels in `CHANGE MASTER` statement.

2017-05-01 10:07 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/test/inc/common.sh
> +  FOR CHANNEL 'master-$master_id_arg';
Added explicit argument `USE_CHANNELS` to the `setup_slave`.

2017-05-01 10:08 UTC, VasilyNemkov commented
Fixed, new param build: http://jenkins.percona.com/view/PXB%202.3/job/percona-xtrabackup-2.4-param/187/

2017-05-01 23:33 UTC, gl-sergei commented
Thanks. Looks good to me.

2017-05-01 23:33 UTC, gl-sergei approved these changes

2017-05-02 04:55 UTC, merged