Bug #1600656: Feature request: Include xtrabackup_info to extra-lsn-dir
percona/percona-xtrabackup pull request #364
Opened 2017-05-03 06:23 UTC by VasilyNemkov

Creating an extra copy of the xtrabackup_info in the directory specified with --extra-lsndir
And a test that verifies that it matches the one from the stream.

2017-05-04 09:52 UTC, VasilyNemkov commented
Param build: http://jenkins.percona.com/view/PXB%202.3/job/percona-xtrabackup-2.3-param/280/

2017-05-05 05:35 UTC, gl-sergei requested changes
Looks good. Just one minor issue.

2017-05-05 05:35 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +	bool result = write_to_file(filepath, xtrabackup_info_data);
write_to_file returns my_bool, but result is assigned to my_bool. Please either change write_to_file or the type of "result" variable.

2017-05-05 06:12 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +	bool result = write_to_file(filepath, xtrabackup_info_data);
Fixed

2017-05-05 06:13 UTC, VasilyNemkov commented
The `bool/my_bool` issue was fixed.

2017-05-08 04:41 UTC, gl-sergei approved these changes

2017-05-08 04:41 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	      sizeof(xb_stream_format_name)/sizeof(xb_stream_format_name[0]));
There is `array_elements` in my_global.h which does exactly the same thing

2017-05-08 04:49 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	      sizeof(xb_stream_format_name)/sizeof(xb_stream_format_name[0]));
Fixed

2017-05-10 08:01 UTC, merged