Bug 1671437: Waiting for master thread to be suspended
percona/percona-xtrabackup pull request #378
Opened 2017-06-25 11:22 UTC by gl-sergei

Commit c5aca380511 attempted to fix assertion
`srv_get_active_thread_type() == SRV_NONE', but did it wrong way by
exiting purge thread while there was still some work to do. It caused
transaction not being able to rollback and xtrabackup would loop
indefinitely.

This commit reverts that change and instead makes server don't switch to
`SRV_SHUTDOWN_FLUSH_PHASE' until there is no active transactions.

2017-06-25 11:22 UTC, gl-sergei commented
http://jenkins.percona.com/view/PXB%202.4/job/percona-xtrabackup-2.4-param/214/

2017-06-27 10:39 UTC, VasilyNemkov requested changes
There is an issues that has to be addressed.

2017-06-27 10:39 UTC, VasilyNemkov commented on storage/innobase/log/log0log.cc
> +			&& trx_rollback_or_clean_is_active)) {
This may cause a crash, please take a look at `case SRV_NONE:` below.

2017-06-27 10:47 UTC, gl-sergei commented on storage/innobase/log/log0log.cc
> +			&& trx_rollback_or_clean_is_active)) {
Thank you! Indeed, I missed one more bit for this patch. Should be fine now

2017-06-28 05:09 UTC, gl-sergei commented
Fixed. New Jenkins http://jenkins.percona.com/view/PXB%202.4/job/percona-xtrabackup-2.4-param/220/

2017-06-29 09:50 UTC, VasilyNemkov approved these changes
Looks good now.

2017-06-30 05:01 UTC, merged