Rewrite xbcrypt using ds_decrypt
percona/percona-xtrabackup pull request #407
Opened 2017-08-01 15:15 UTC by VasilyNemkov

Blueprint:
[https://blueprints.launchpad.net/percona-xtrabackup/+spec/xbcrypt-ds-decrypt]

Using ds_encrypt and ds_decrypt in xbcrypt for encryption and decryption.
Minor fixes to the ds_encrypt and ds_decrypt.

2017-08-02 04:55 UTC, VasilyNemkov commented
param-build: http://jenkins.percona.com/job/percona-xtrabackup-2.3-param/317/

2017-08-04 08:26 UTC, gl-sergei requested changes
Looks good, just few minor comments

2017-08-04 08:26 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/ds_decrypt.c
> +my_bool		ds_decrypt_modify_file_extension = TRUE;
small formatting issue - please make these two lines aligned

2017-08-04 08:26 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/ds_encrypt.c
> +my_bool		ds_encrypt_modify_file_extension = TRUE;
same formatting issue here as well

2017-08-04 08:26 UTC, gl-sergei commented on storage/innobase/xtrabackup/test/t/xbcrypt.sh
> +parent_dir=$TEST_VAR_ROOT
Nice catch regarding use if unbind variable `topdir`!

2017-08-04 08:26 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/xbcrypt.c
> +/* Need the following definitions to avoid linking with ds_*.o and their link
But we do link with ds_*?

2017-08-04 08:26 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/ds_encrypt.c
> +	if (ds_encrypt_modify_file_extension) {
Please add the comment what is this needed for.

2017-08-04 08:26 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/ds_decrypt.c
> +	if (ds_decrypt_modify_file_extension) {
Please add the comment what is this needed for.

2017-08-04 12:18 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/src/xbcrypt.c
> +/* Need the following definitions to avoid linking with ds_*.o and their link
Nope, in fact we build few files of datasink as source files for the xbcrypt, the same way it is used in xbstream.

2017-08-05 06:53 UTC, VasilyNemkov commented
Fixed

2017-08-10 02:09 UTC, gl-sergei approved these changes

2017-08-10 02:09 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/ds_decrypt.c
> +	   Here implicit extension modification causes more trouble than good.
+1

2017-08-10 02:09 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/ds_encrypt.c
> +	   See also ds_decrypt_modify_file_extension . */
+1

2017-08-15 08:25 UTC, merged