Bug 1707918: using innobackupx with --slave-info output file xtraback…
percona/percona-xtrabackup pull request #408
Opened 2017-08-03 14:36 UTC by VasilyNemkov

…up_slave_info does not contain slave information in 2.4.8

Fixed xtrabackup_slave_info creation so the archive header is set properly now.
Added a test.

2017-08-03 14:36 UTC, VasilyNemkov commented
bug: https://bugs.launchpad.net/percona-xtrabackup/2.3/+bug/1707918
param-build: http://jenkins.percona.com/job/percona-xtrabackup-2.4-param-medium/18/

2017-08-03 14:48 UTC, berlincount commented on storage/innobase/xtrabackup/test/t/bug1707918.sh
> +  die "tar-ed xtrabackup_slave_info has wronf size"
slight typo here :)

2017-08-04 05:08 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/test/t/bug1707918.sh
> +  die "tar-ed xtrabackup_slave_info has wronf size"
Fixed, you have a keen eye!

2017-08-04 06:39 UTC, gl-sergei approved these changes
I like code changes. Please consider to put some more work on the test case.

2017-08-04 06:39 UTC, gl-sergei commented on storage/innobase/xtrabackup/test/t/bug1707918.sh
> +xtrabackup --backup --slave-info --stream=tar > $topdir/backup/xtrabackup.tar
Please add one more - with `xbstream`. It was not affected by the bug, but still we will have better coverage.

2017-08-04 06:39 UTC, gl-sergei commented on storage/innobase/xtrabackup/test/t/bug1707918.sh
> +# Files do differ, but should be of approximately same size
instead of comparing sizes, maybe just use regex? We know that it contains two lines and there are ready to go regexes in `ib_slave_info.sh`

2017-08-04 06:39 UTC, gl-sergei commented on storage/innobase/xtrabackup/test/t/bug1707918.sh
> +load_sakila
We don't need to load sakila database for this test. We can test on much smaller dataset and save some precious Jenkins time :) Even further, I think this test can be combined with `ib_slave_info.sh`, we can make streaming backup there along with local backup.

2017-08-04 06:40 UTC, gl-sergei requested changes
Oops. Set wrong status

2017-08-04 06:43 UTC, gl-sergei commented
Please also add bug analysis to the commit message

2017-08-04 09:47 UTC, VasilyNemkov commented on storage/innobase/xtrabackup/test/t/bug1707918.sh
> +load_sakila
Good point

2017-08-05 07:14 UTC, VasilyNemkov commented
Fixed

2017-08-10 02:24 UTC, gl-sergei approved these changes

2017-08-10 04:16 UTC, merged