Release notes for the 2.4.10 PXB release.
percona/percona-xtrabackup pull request #483
Opened 2018-03-26 23:48 UTC by fiowro

2018-03-27 07:58 UTC, gl-sergei requested changes

2018-03-27 07:58 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +
Please also mention that now PXB is based on MySQL 5.7.19

2018-03-27 07:58 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +* When there was error in taking backup of a table from bad tablespace,
xtrabackup skipped tablespaces with corrupted first page instead of aborting the backup

2018-03-27 07:58 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +  :jirabug:`PXC-792`.
Please check bug reference, is it really PXC- issue?

2018-03-27 07:58 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +* Compilation under Mac OS X was broken. Bug fixed :jirabug:`PXC-796`.
Please check bug reference, is it really PXC- issue?

2018-03-27 07:58 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +"COMPLETED OK" and finishing with zero return code. Bug fixed :jirabug:`PXC-1497`.
Please check bug reference, is it really PXC- issue?

2018-03-27 07:58 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +* Decrypt operation was failing due to regression in |Percona XtraBackup| 2.4.9.
xbcrypt with "--encrypt-key-file seems" option was failing. Please check bug reference, is it really PXC- issue?

2018-03-28 03:26 UTC, gl-sergei requested changes

2018-03-28 03:26 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +* When there was error in taking backup of a table from bad tablespace,
"When there was error in taking backup of a table from bad tablespace," is not needed here. The issue was that when PXB met tablespace with corrupted first page, it skipped that tablespace. Now it aborts the backup.

2018-03-28 03:26 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +* xbcrypt with ``--encrypt-key-file seems`` option was failing due to regression
s/--encrypt-key-file seems/--encrypt-key-file/

2018-03-28 03:26 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +* Usage of both ``--lock-ddl`` and ``--lock-ddl-per-table`` options caused
Simultaneous usage

2018-03-28 14:36 UTC, gl-sergei approved these changes
LGTM

2018-03-29 14:19 UTC, hrvojem commented on storage/innobase/xtrabackup/doc/source/release-notes/2.4/2.4.10.rst
> +<http://www.percona.com/downloads/XtraBackup/Percona-XtraBackup-2.4.10/>`_ and
Release date is 30th

2018-03-30 14:55 UTC, merged