2.4 xb 1548
percona/percona-xtrabackup pull request #506
Opened 2018-06-26 03:06 UTC by altmannmarcelo

This implements #PXB-1548.

Buffer pool dump happens at the beginning of backup if `--dump-innodb-buffer-pool` is set. 
Prior to copying `ib_buffer_pool` it checks if current `SHOW STATUS LIKE 'Innodb_buffer_pool_dump_status'` contains the string `dump completed at`. If dump is still in progress, the tool keeps checking untill `--dump-innodb-buffer-pool-timeout=N` seconds has elapsed since we originally started the dump.

User can choose to change the default `innodb_buffer_pool_dump_pct`. If `--dump-innodb-buffer-pool-pct` is set, it stores the current MySQL `innodb_buffer_pool_dump_pct` value, then it changes it to the desired percentage. After the check in the end of backup, orginal values is restored back.

3 new parameters have been added:
`--dump-innodb-buffer-pool` - When set, this will trigger dump of buffer pool prior to copying ib_buffer_pool
`--dump-innodb-buffer-pool-timeout=N` - This controlls for how long (in seconds) to wait for dump of buffer pool before moving on. (default: 10)
`--dump-innodb-buffer-pool-pct=N` - This controlls the percentage of buffer pool to dump. If set, xtrabackup will save current MySQL value, change to the desired value, once dump is completed or it aborts due to time out, it will change it back to original value.

2018-06-27 07:45 UTC, gl-sergei commented
Hi @altmannmarcelo ! Are you willing to continue to work on this patch? If so, I would ask to you to start with adding a test case (you can see examples in xtrabackup/test/t/ directory). Then fix code formatting. Please also make sure to check that patch doesn't break anything on older MySQL versions.

2018-06-30 22:07 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +		original_innodb_buffer_pool_dump_pct =
@gl-sergei I'm not sure is ok to break the value assignment into 2 line, but leaving it on a single line would exceed 80 characters.

2018-06-30 22:27 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +		atoi(innodb_buffer_pool_dump_pct);
@gl-sergei I'm not sure is ok to break the value assignment into 2 line, but leaving it on a single line would exceed 80 characters.

2018-06-30 22:30 UTC, altmannmarcelo commented
Tested on not supported version and it works fine. Even if you pass `--dump-innodb-buffer-pool` it won't attempt to run the dump.

2018-07-16 07:06 UTC, gl-sergei requested changes

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +		if(opt_dump_innodb_buffer_pool && has_innodb_buffer_pool_dump()) {
s/if(opt/if (opt/

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if((server_flavor == FLAVOR_PERCONA_SERVER ||
s/if((server_flavor/if ((server_flavor/

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if(server_flavor == FLAVOR_MARIADB && mysql_server_version >= 10000) {
s/if(server_flavor/if (server_flavor/

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if((server_flavor == FLAVOR_PERCONA_SERVER ||
s/if((server_flavor/if ((server_flavor/

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if(server_flavor == FLAVOR_MARIADB && mysql_server_version >= 10110) {
s/if(server_flavor/if (server_flavor/

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if(opt_dump_innodb_buffer_pool_pct != 0 &&
s/if(opt_dump_innodb_buffer_pool_pct/if (opt_dump_innodb_buffer_pool_pct/

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +			{"innodb_buffer_pool_dump_pct", &innodb_buffer_pool_dump_pct},
Line is too long

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +			"SHOW GLOBAL VARIABLES LIKE 'innodb_buffer_pool_dump_pct'",
Line is too long and extra trailing space

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +		atoi(innodb_buffer_pool_dump_pct);
It is fine to break, please also add extra tab on second line

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +		xb_mysql_query(mysql_connection, change_bp_dump_pct_query, false);
This line is too long

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +			{"Innodb_buffer_pool_dump_status", &innodb_buffer_pool_dump_status},
This line and entire next block are too long

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if(opt_dump_innodb_buffer_pool_pct != 0 &&
s/if(opt_dump_innodb_buffer_pool/if (opt_dump_innodb_buffer_pool/

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +		if(opt_dump_innodb_buffer_pool && has_innodb_buffer_pool_dump()) {
s/if(opt_dump_innodb_buffer_pool/if (opt_dump_innodb_buffer_pool/

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +
Whitespace on empty line.

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +
Whitespace on empty line

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if((server_flavor == FLAVOR_PERCONA_SERVER ||
trailing whitespace

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if((server_flavor == FLAVOR_PERCONA_SERVER ||
trailing whitespace

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if(opt_dump_innodb_buffer_pool_pct != 0 &&
trailing whitespace

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +			"SHOW GLOBAL VARIABLES LIKE 'innodb_buffer_pool_dump_pct'",
trailing whitespace

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +		original_innodb_buffer_pool_dump_pct =
trailing whitespace

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +		if(innodb_buffer_pool_dump_start_time +
Missing space after "if" and extra trailing whitespace

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +	if(opt_dump_innodb_buffer_pool_pct != 0 &&
trailing whitespace

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.cc
> +bool
Please make it static

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.h
> +bool
Please make it static and local to `backup_mysql`

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_mysql.h
> +has_innodb_buffer_pool_dump();
Consider making it static and local to `backup_mysql`, `check_dump_buffer_pool` could be made the only entry point.

2018-07-16 07:06 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_copy.cc
>  	if (!opt_rsync) {
Can we make it work with rsync?

2018-07-30 21:13 UTC, altmannmarcelo commented
@gl-sergei adjusted code as per your review

2018-10-30 15:56 UTC, altmannmarcelo commented
Implemented in a single commit over https://github.com/percona/percona-xtrabackup/pull/563 . Thanks, @gl-sergei for the review.

2018-10-30 15:56 UTC, closed without merging