Fixed pxb-1614 by updating description of version-check option
percona/percona-xtrabackup pull request #512
Opened 2018-08-15 17:17 UTC by borys-belinsky

2018-08-15 17:23 UTC, gl-sergei requested changes

2018-08-15 17:23 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/innobackupex/innobackupex_option_reference.rst
>  .. option:: --version-check
Is there PR for 2.3? The option name is `--no-version-check` and it is OFF by default, it means that data is sent by default. xtrabackup has the same option, please also add it to xtrabackup option reference.

2018-08-15 17:23 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/innobackupex/innobackupex_option_reference.rst
> +   When this option is specified, innobackupex will perform a version check
When `--no-version-check` is specified, innobackupex/xtrabackup will **skip** a version check. When it is not specified (default) innobackupex/xtrabackup will perform version check.

2018-08-15 17:33 UTC, borys-belinsky commented on storage/innobase/xtrabackup/doc/source/innobackupex/innobackupex_option_reference.rst
>  .. option:: --version-check
Do I understand you correctly that 2.3 should also be updated?

2018-08-15 17:38 UTC, dbpercona commented on storage/innobase/xtrabackup/doc/source/innobackupex/innobackupex_option_reference.rst
> +   When this option is specified, innobackupex will perform a version check
does innobackupex/xtrabackup do the version check with every execution?  even with --help  ?   Or only before backup, restore, and prepare?

2018-08-15 17:40 UTC, dbpercona commented on storage/innobase/xtrabackup/doc/source/innobackupex/innobackupex_option_reference.rst
> +   - Operation system name
should be "Operating system"

2018-08-15 17:47 UTC, borys-belinsky commented on storage/innobase/xtrabackup/doc/source/innobackupex/innobackupex_option_reference.rst
>  .. option:: --version-check
Also, what happens if the user specifies both no-version-check and version-check?

2018-08-15 18:47 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/innobackupex/innobackupex_option_reference.rst
>  .. option:: --version-check
there is no `version-check`, just `no-version-check`

2018-08-15 18:48 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/innobackupex/innobackupex_option_reference.rst
>  .. option:: --version-check
2.3 behaviour is the same, it would be logical to update both

2018-08-15 18:49 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/innobackupex/innobackupex_option_reference.rst
> +   When this option is specified, innobackupex will perform a version check
Only before backup. Not before prepare, not for other modes.

2018-08-16 18:55 UTC, gl-sergei commented
Is it ready for review? Please update xtrabackup option reference too. As per my comment "xtrabackup has the same option, please also add it to xtrabackup option reference."

2018-08-30 16:57 UTC, gl-sergei approved these changes
LGTM. Thanks!

2018-08-30 17:15 UTC, merged