PXB-1665: Fix two issues reported by ubsan
percona/percona-xtrabackup pull request #545
Opened 2018-09-26 09:29 UTC by dutow

2018-09-26 10:06 UTC, gl-sergei requested changes

2018-09-26 10:06 UTC, gl-sergei commented on storage/innobase/buf/buf0dblwr.cc
> +      ut_ad(recv_sys != nullptr);
better to replace this with `ut_error` ? as per comment in `fsp0sysspace.cc` "XtraBackup never loads corrupted pages from the doublewrite buffer"

2018-09-27 08:39 UTC, dutow commented
Updated.

2018-09-27 09:09 UTC, gl-sergei approved these changes

2018-09-27 10:15 UTC, merged