PXB-1908: Release notes - v8.0.7
percona/percona-xtrabackup pull request #741
Opened 2019-08-06 12:45 UTC by borys-belinsky

2019-08-06 12:52 UTC, gl-sergei requested changes

2019-08-06 12:52 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.7.rst
> +In release |release|, |pxb.name| introduces the encryption of the system
xtrabackup does not introduce "encryption of the system tablespace", it now supports backups and prepare of the databases containing encrypted system tablespace (https://www.percona.com/doc/percona-server/5.7/management/data_at_rest_encryption.html#innodb_sys_tablespace_encrypt)

also, xtrabackup now supports encrypted mysql tablespace as well

2019-08-06 12:52 UTC, gl-sergei commented on storage/innobase/xtrabackup/doc/source/release-notes/8.0/8.0.7.rst
> +directly which improves the speed of compression. Use `--compress=lz4` to use
could be better to say that compressed backups can now use lz4 compression algorithm in addition to quicklz

2019-08-06 13:15 UTC, gl-sergei approved these changes

2019-08-07 12:10 UTC, gl-sergei approved these changes

2019-08-07 12:48 UTC, merged

2019-08-07 14:30 UTC, tduzan-te reviewed
two misspellings, otherwise okay by me

2019-08-07 14:30 UTC, tduzan commented on storage/innobase/xtrabackup/doc/source/howtos/recipes_xbk_compressed.rst
> +If you used the ``lz4`` compression algoritm change this script to search for ``*.lz4`` files:
`algorithm` is misspelled here

2019-08-07 14:30 UTC, tduzan commented on storage/innobase/xtrabackup/doc/source/xtrabackup_bin/xbk_option_reference.rst
> +   If you used the ``lz4`` compression algoritm to compress the files
`algorithm` is misspelled here