PXB-1957 Disk file mismatch in copying sparse file
percona/percona-xtrabackup pull request #775
Opened 2019-11-19 04:40 UTC by rahulmalik87

PXB-1957 Disk file mismatch in copying the sparse file

Problem:
While copying sparse tablespace, if the last page is sparse. then
PXB was not copying it correctly, resulting in a mismatch of size on disk

Fix
completely copy the last page.

2019-11-19 04:40 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=775) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtrabackup?pullRequest=775) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtrabackup?pullRequest=775) it.</sub>

2019-11-19 05:03 UTC, gl-sergei requested changes

2019-11-19 05:03 UTC, gl-sergei commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +        if (i != total_pages) {
won't
```
      if ((Compression::is_compressed_page(page) ||
          fil_page_get_type(page) == FIL_PAGE_COMPRESSED_AND_ENCRYPTED) && !last_page_of_file) {
```
be better condition?

Also, the last page in the buffer is not always the last page of file. This patch will write non-sparse page every 10M.

2019-11-19 05:03 UTC, gl-sergei commented on storage/innobase/xtrabackup/test/t/page_compression.sh
> +if is_sparse_file $mysql_datadir/test/t1.ibd ; then
changes to the test case looks good to me. thank you for fixing it :)

2019-11-20 11:46 UTC, gl-sergei approved these changes

2019-11-25 05:12 UTC, merged