PXB-1961 Prepare of full backup fails for encrypted tables with Generic
percona/percona-xtrabackup pull request #853
Opened 2020-04-24 08:04 UTC by rahulmalik87

Problem:
PXB is not handling PS encryption types.

Analysis:
PS support addition encrytion types like keyring which is not handled.
This bugs only adresses encryption='n'

Fix:
Handle and process ENCRYPTION_KEY_MAGIC_PS_V2 in PXB

2020-04-28 10:02 UTC, satya-bodapati requested changes

2020-04-28 10:02 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +            break;
this works? surprising... the v2 writer is only writing KERYING_ENCRYPTION_INFO_MAX_SIZE bytes.

mlog_write_string(page + offset, encrypt_info,
                    KERYING_ENCRYPTION_INFO_MAX_SIZE, mtr);

Also you need to handle V1 KERYING_ENCRYPTION_INFO_MAX_SIZE_V1 bytes.

2020-04-28 10:16 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +            break;
Also there should be ptr null check

2020-10-08 13:53 UTC, rahulmalik87 commented
update the test case @satya-bodapati. it passed locally. 

Using /home/rahul.malik/MySQL/src/x8/bld/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against MySQL 8.0.21-debug (InnoDB 8.0.21)
Using 'xtrabackup' as xtrabackup binary
Using 8 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
xbcloud                                  w1	[passed]    106
==============================================================================
Spent 106 of 124 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output
{smm-12-d40aec x8 o8 test}$

2021-05-19 06:46 UTC, closed without merging