PXB-2127 xbcloud Fails to upload with empty database
percona/percona-xtrabackup pull request #872
Opened 2020-06-08 07:53 UTC by rahulmalik87

Problem:
Xbcloud fails to upload data in minio with empty database.

Analysis:
xbcloud is placing dummy file /db.opt in empty directory.
Path becomes /path/to//db.opt instead of /path/to/db.opt
minio assue path of the file as "/db.opt" and throws error
unspported file name.

Fix:
intead of /db.opt use db.opt as output file

2020-06-08 09:41 UTC, satya-bodapati requested changes
Regarding testcase, any existing test to cover?

2020-06-08 09:41 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/backup_copy.cc
> +					"%sdb.opt", node.filepath);
this is a bit risky. What if the path doesn't end with trailing slash? My suggestion is to keep this %s/db.opt thing.  Add code to remove trailing slash in path.

2020-06-08 09:42 UTC, satya-bodapati commented
Also please mention that "//" causes problems with minio S3 blah blah.. in the commit message.

2020-06-08 09:43 UTC, satya-bodapati commented
And also add the reason for this fake file in empty dir

2020-06-08 09:43 UTC, satya-bodapati commented
Jenkins test link plz

2020-06-09 13:38 UTC, rahulmalik87 commented
> Regarding testcase, any existing test to cover?

added the testcase

2020-06-10 09:25 UTC, closed without merging