ENG-197: [PXB2.4] Introduce linking script
percona/percona-xtrabackup pull request #900
Opened 2020-06-26 00:23 UTC by Sudokamikaze

2020-07-01 13:58 UTC, EvgeniyPatlan reviewed
looks ok

2020-07-02 07:10 UTC, Sudokamikaze commented
Changed: Reverted innodb commit, added `epel-release` to test suite

2020-07-02 11:05 UTC, EvgeniyPatlan requested changes

2020-07-02 11:05 UTC, EvgeniyPatlan commented on storage/innobase/xtrabackup/test/bootstrap.sh
> +arch="$(uname -m)"
```suggestion
arch=$(uname -m)
```

2020-07-02 11:05 UTC, EvgeniyPatlan commented on storage/innobase/xtrabackup/utils/build-binary.sh
> +INSTALLDIR="$WORKDIR_ABS/$BASEINSTALLDIR/percona-xtrabackup-$XTRABACKUP_VERSION-$(uname -s)-$(uname -m)$GLIBC_VER"   # Make it absolute
where is GLIBC_VER defined?

2020-07-02 11:14 UTC, EvgeniyPatlan approved these changes

2020-07-06 06:18 UTC, vorsel approved these changes

2020-07-06 19:46 UTC, merged