PXB-2186: Explain running in Docker container
percona/percona-xtrabackup pull request #901
Opened 2020-06-30 13:56 UTC by borys-belinsky

2020-06-30 15:34 UTC, kathy-williamson approved these changes

2020-07-01 12:23 UTC, EvgeniyPatlan requested changes

2020-07-01 12:23 UTC, EvgeniyPatlan commented on storage/innobase/xtrabackup/doc/source/installation/docker.rst
> +newly created containers: perconalab/percona-xtrabackup. |docker| images for
As it is already tested we need to put image under percona account on docker hub and do not tell anything regarding perconalab

2020-07-02 11:07 UTC, EvgeniyPatlan approved these changes

2020-07-06 10:46 UTC, merged