PXB-2229 Error out backup if redo logging is disabled
percona/percona-xtrabackup pull request #926
Opened 2020-08-11 07:36 UTC by rahulmalik87

Problem:
--------
From MySQL 8.0.21 release, redo logs can be disabled and enabled dynamically
using ALTER INSTANCE [ENABLE/DISABLE] REDO_LOG. (This is meant only for initial
data loading stages)

PXB relies on replaying redo logs to get consistent backups.

Fix:
----
Detect whether REDOLOG is disabled or not and error out as follows

1. Redo is disabled before backup                              : Backup failure
2. Redo is disabled and enabled before backup                  : Successful backup
3. Redo is enabled at start of backup, but disabled before end
of backup (applies to both full and incremental backups)     : Backup failure
4. Redo is disabled and enabled again between Full and
Incremental backup                                            : Successful backup

Special case:
-------------

If redo is enabled at startup of backup but during the process of backup it is
disabled and enabled before the backup completes, it will result in inconsistent
backups. PXB may not error out in this scenario.

Users are advised to use --lock-ddl=ON with PXB to avoid users disabling and
enabling redo logs "during the backups"

2020-08-11 08:28 UTC, satya-bodapati requested changes

2020-08-11 08:28 UTC, satya-bodapati commented on storage/innobase/xtrabackup/test/t/alter_redo.sh
> +sleep 2 #sleep so some of data is loaded by load_sakila
with sleep, testcase is not reliable. Just use load_sakila without the &

and add verify

2020-08-11 08:28 UTC, satya-bodapati commented on storage/innobase/xtrabackup/test/t/alter_redo.sh
> +mysql -e "alter instance enable innodb redo_log"
with sleep, testcase is not reliable. Just use load_sakila without the &

and add verify

2020-08-11 08:28 UTC, satya-bodapati commented on storage/innobase/xtrabackup/test/t/alter_redo.sh
> +mysql -e "alter instance enable innodb redo_log"
This scenario is then duplicate.. may be remove

2020-08-11 08:28 UTC, satya-bodapati commented on storage/innobase/xtrabackup/test/t/alter_redo.sh
> +start_server
rename test to alter_instance_redo.sh

2020-08-11 12:06 UTC, rahulmalik87 commented
https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param/lastCompletedBuild/testReport/

2020-08-12 05:44 UTC, satya-bodapati approved these changes

2020-08-12 06:40 UTC, merged