PXB-2215 Importing tablespace where character set of table is specifi…
percona/percona-xtrabackup pull request #928
Opened 2020-08-12 07:03 UTC by rahulmalik87

…ed fails with (Column x precise type mismatch.)

Problem:
--------
pxb is not properly calulating pack_lenght of varchar column
which could end up calculating wrong column_lenght.

Fix:
---
calculate the pack_lenght based on column's actual char_length
and not the calcuated field_length

2020-08-12 07:06 UTC, satya-bodapati requested changes
Please fix the typos in the commit message "lenght".

and Jenkins link

2020-08-12 07:36 UTC, rahulmalik87 commented
https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param/146/

2020-08-12 10:28 UTC, satya-bodapati approved these changes
LGTM!

2020-08-12 10:29 UTC, merged

2020-08-26 14:46 UTC, it-percona commented
Comment to trigger webhook.