8.0 Implemented PXB-2254 (Redesign --lock-ddl-per-table)
percona/percona-xtrabackup pull request #939
Opened 2020-08-25 17:49 UTC by altmannmarcelo

https://jira.percona.com/browse/PXB-2254

The current implementation of --lock-ddl-per-table works as follow:

Creates a dedicated mysql connection for MDL and start a transaction.
Start to scan directories (databases) looking for .ibd files.
For each .ibd file it tries to transalate the space id recorded on
the file header to a table (or tables in case of shared tablespace).
If it finds a table associate with the .ibd (or tables) it executes a
SELECT * FROM table LIMIT 1 using the dedicated connection for MDL.
From this point forward, the table is locked and new DDL will be
blocked until the MDL connection commits.
With this, it has been assumed that if a MLOG_LOAD_INDEX event has
been generated (https://dev.mysql.com/worklog/task/?id=7277) it's safe
to continue since we have taken MDL on the table we are copying.
This design has a few flaws:

FTS have their own tablespace, which is been copied without
MDL protection.
Ongoing DDL that generate temporary table (#sql...) are copied
without MDL protection.
When creating FTS for the first time, MySQL will have to create a
tmp table (Item 2) and FTS files (Item 1) are pointing to temp table.
Table space IDs for FTS or regular tables will change if you
DROP and then CREATE the same FTS/TABLE. MDL lock query will fail to
find the corresponding table but file will exist, thus will be copied
without MDL protection.
If a table is created after xtrabackup has gathered the list of
.ibd's to copy and before the backup has finished, this particular
table will be part of the backup as it will be contained within the
redo log. However, if a bulk index load operations have been performed
( MLOG_INDEX_LOAD has been written to the redo log), this change to the
data file will not be tracked and will be missed from the backup.
This commit changes to:

MDL is taken at the beginning of backup for all know tables at
that time, before we start to copy individual .ibd files.
A new flag controls whatever MDL step has been completed or not.
Before MDL from step 1 is completed, redo follow thread accept
parsing MLOG_INDEX_LOAD. At this point is still safe to accept it since
we have not started to copy .ibd files. After MDL part is completed,
mdl_taken changes to true and parsing a MLOG_INDEX_LOAD causes the
backup to abort.
Before we execute the MDL query for a specific entry from
INNODB_SYS_TABLES, we validate it against a regexp for a FTS file name,
if we are manipulating a FTS index, we translate it to the corresponding
table name.
If for any reason we cannot execute the MDL lock query (for example,
a DDL is ongoing and we are manipulating a file starting with #sql-)
we do not abort the backup. We will only abort if a subsequent
MLOG_INDEX_LOAD is found by the redo follow thread during the backup.
We identify temporary tables (#sql-) and skip trying to lock them.
No reason to attempt to query it as it will always result in an error.
MDL query changed to not bring any row back. This is enough for
taking a MDL while saving the server from bringing any row back.

2020-08-25 17:50 UTC, altmannmarcelo commented
https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/317/

2020-09-02 14:16 UTC, altmannmarcelo commented
@satya-bodapati I spoke with @georgelorchpercona yesterday, we are good to go in terms of calling `--lock-ddl-per-table` deprecated on PXB 8.0

2020-09-02 14:18 UTC, satya-bodapati commented
> @satya-bodapati I spoke with @georgelorchpercona yesterday, we are good to go in terms of calling `--lock-ddl-per-table` deprecated on PXB 8.0

ok @altmannmarcelo  did you add the deprecation message ?

2020-09-02 14:19 UTC, altmannmarcelo commented
> > @satya-bodapati I spoke with @georgelorchpercona yesterday, we are good to go in terms of calling `--lock-ddl-per-table` deprecated on PXB 8.0
> 
> ok @altmannmarcelo did you add the deprecation message ?

@satya-bodapati yes - https://github.com/percona/percona-xtrabackup/pull/939/files#diff-29fd8beae6c2cfce456b51a213d966eeR6857

2020-09-02 14:20 UTC, satya-bodapati commented
> > > @satya-bodapati I spoke with @georgelorchpercona yesterday, we are good to go in terms of calling `--lock-ddl-per-table` deprecated on PXB 8.0
> > 
> > 
> > ok @altmannmarcelo did you add the deprecation message ?
> 
> @satya-bodapati yes - https://github.com/percona/percona-xtrabackup/pull/939/files#diff-29fd8beae6c2cfce456b51a213d966eeR6857

ok @altmannmarcelo, will check tomorrow

2020-09-03 14:09 UTC, satya-bodapati requested changes

2020-09-03 14:09 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/redo_log.cc
> +  mdl_taken = true;
One doubt, if opt_lock_ddl_per_table is OFF (mdl is not taken), we still set mdl_taken= true. Is ithis intentional?

2020-09-03 14:14 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/src/redo_log.cc
> +  mdl_taken = true;
@satya-bodapati yes, because regardless of MDL been taken or not, later at `log0recv.cc` https://github.com/percona/percona-xtrabackup/pull/939/files#diff-ec5cdb94d89780d34753579b799e83ebR1658 we cannot accept continuing the backup if we parse `MLOG_INDEX_LOAD`. Before we were only entering that condition if `lock-ddl-per-table` was off, assuming that if it was ON it was safe to continue the backup even though we parsed `MLOG_INDEX_LOAD`.

2020-09-04 06:50 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/redo_log.cc
> +  mdl_taken = true;
Ok, with LOCK INSTANCE/LOCK_TABLES_FOR_BACKUP taken earlier, we wouldn't see MLOG_INDEX_LOAD. So the setting mdl_taken=true is OK for these scenarios.

2020-09-04 06:51 UTC, satya-bodapati approved these changes

2020-09-04 12:18 UTC, merged