PXB-2258 document --lock-ddl and --lock-ddl-per-table (2.4)
percona/percona-xtrabackup pull request #947
Opened 2020-09-11 11:58 UTC by patrickbirch

new file:   source/advanced/locks.rst
	modified:   source/faq.rst
	modified:   source/index.rst

2020-09-14 11:34 UTC, kathy-williamson approved these changes

2020-10-13 09:32 UTC, altmannmarcelo requested changes

2020-10-13 09:32 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/advanced/locks.rst
> +|Percona XtraBackup| has also implemented ``--lock-ddl-per-table``, which blocks DDL statements but allows metadata locks (MDL).
```suggestion
|Percona XtraBackup| has also implemented ``--lock-ddl-per-table``, which blocks DDL statements by using metadata locks (MDL).
```

2020-10-13 09:32 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/advanced/locks.rst
> +The following procedures describe a simplified backup operation:
```suggestion
The following procedures describe a simplified backup operation when using ``--lock-ddl-per-table``:
```

2020-10-13 09:32 UTC, altmannmarcelo commented on storage/innobase/xtrabackup/doc/source/advanced/locks.rst
> +* After the first scan has started, the follow new redo log events thread is initiated. This thread stops the backup process if an ``MLOG_INDEX_LOAD`` event is found.
```suggestion
* After the first scan has completed, the follow redo log thread is initiated. This thread stops the backup process if an ``MLOG_INDEX_LOAD`` event is found.
```

2020-11-02 11:57 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/advanced/locks.rst
> +The following procedures describe a simplified backup operation:
Updated.

2020-11-02 11:57 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/advanced/locks.rst
> +* After the first scan has started, the follow new redo log events thread is initiated. This thread stops the backup process if an ``MLOG_INDEX_LOAD`` event is found.
updated.

2020-11-02 11:57 UTC, patrickbirch commented on storage/innobase/xtrabackup/doc/source/advanced/locks.rst
> +|Percona XtraBackup| has also implemented ``--lock-ddl-per-table``, which blocks DDL statements but allows metadata locks (MDL).
updated.

2020-12-08 15:54 UTC, altmannmarcelo approved these changes
LGTM

2020-12-08 15:56 UTC, merged