PXB-2337: Switch ZLIB & ZSTD to bundled
percona/percona-xtrabackup pull request #996
Opened 2020-11-05 09:52 UTC by Sudokamikaze

Builds: TBA

2020-11-05 14:14 UTC, EvgeniyPatlan requested changes

2020-11-05 14:14 UTC, EvgeniyPatlan commented on storage/innobase/xtrabackup/utils/build-binary.sh
> +          -DDOWNLOAD_BOOST=1 -DWITH_BOOST=${WORKDIR_ABS}/libboost  \
please remove extra space

2020-11-05 14:51 UTC, Sudokamikaze commented on storage/innobase/xtrabackup/utils/build-binary.sh
> +          -DDOWNLOAD_BOOST=1 -DWITH_BOOST=${WORKDIR_ABS}/libboost  \
Fixed, thanks

2020-11-06 06:17 UTC, EvgeniyPatlan approved these changes

2020-11-06 10:07 UTC, merged